#!/usr/bin/env python3
"""
race_simulator.py  –  Box Box Box Race Simulator
=================================================
Reads a race scenario from stdin (JSON) and writes the predicted
finishing order to stdout (JSON).

Parameters are loaded from solution/params.json if it exists
(generated by analysis/discover_params.py).  If that file is
absent, hard-coded fallback values are used — but run the
discovery script first for full accuracy.

Usage:
    cat data/test_cases/inputs/test_001.json | python solution/race_simulator.py
"""

import json
import sys
import os

# ── Load parameters ────────────────────────────────────────────────────────
_PARAMS_FILE = os.path.join(os.path.dirname(__file__), "params.json")

def _load_params():
    if os.path.exists(_PARAMS_FILE):
        with open(_PARAMS_FILE) as f:
            p = json.load(f)
        try:
            return (
                p["COMPOUND_BASE"],
                p["DEGRADATION"],
                p["TEMP_FACTOR"],
                p["DEG_POWER"],
            )
        except (KeyError, TypeError):
            pass

    # ── Fallback (initial estimates — run discover_params.py for accuracy) ──
    compound_base = {"SOFT": -2.5, "MEDIUM": 0.0, "HARD": 2.5}
    degradation   = {"SOFT": 0.04, "MEDIUM": 0.02, "HARD": 0.01}
    temp_factor   = 0.01
    deg_power     = 2.0
    return compound_base, degradation, temp_factor, deg_power


COMPOUND_BASE, DEGRADATION, TEMP_FACTOR, DEG_POWER = _load_params()


# ── Simulation ─────────────────────────────────────────────────────────────

def simulate_race(race_config, strategies):
    """
    Lap-by-lap F1 race simulation.

    Tire age rule (§Tire Age Tracking):
      - tire_age starts at 0 when tyres are fitted
      - tire_age += 1 BEFORE computing the lap time each lap
      - After a pit stop tire_age resets to 0 → next lap = age 1

    Lap time formula:
      lap_time = base_lap_time
               + COMPOUND_BASE[compound]
               + DEGRADATION[compound] * (tire_age ^ DEG_POWER)
               + TEMP_FACTOR * track_temp

    Total race time = sum of all lap times + pit_lane_time per stop

    Finishing positions are ordered by total race time (ascending).
    Ties are broken by original strategy order (Python stable sort).
    """
    base       = race_config["base_lap_time"]
    pit_time   = race_config["pit_lane_time"]
    track_temp = race_config["track_temp"]
    total_laps = race_config["total_laps"]

    results = []

    for strat in strategies.values():
        driver_id    = strat["driver_id"]
        current_tire = strat["starting_tire"]
        total_time   = 0.0
        tire_age     = 0
        pit_idx      = 0
        stops        = strat.get("pit_stops", [])

        for lap in range(1, total_laps + 1):
            # Pre-increment: first lap on fresh tyres is age 1
            tire_age += 1

            lap_time = (
                base
                + COMPOUND_BASE[current_tire]
                + DEGRADATION[current_tire] * (tire_age ** DEG_POWER)
                + TEMP_FACTOR * track_temp
            )
            total_time += lap_time

            # Pit stop occurs at the END of this lap
            if pit_idx < len(stops) and stops[pit_idx]["lap"] == lap:
                total_time   += pit_time
                current_tire  = stops[pit_idx]["to_tire"]
                tire_age      = 0   # fresh set → next lap = age 1
                pit_idx      += 1

        results.append((driver_id, total_time))

    # Stable sort: ties preserve original input order (dict insertion order)
    return [d[0] for d in sorted(results, key=lambda x: x[1])]


# ── Main ───────────────────────────────────────────────────────────────────

def main():
    try:
        data = json.load(sys.stdin)
    except Exception as exc:
        sys.stderr.write(f"Error reading input JSON: {exc}\n")
        sys.exit(1)

    finishing = simulate_race(data["race_config"], data["strategies"])
    output = {
        "race_id":            data["race_id"],
        "finishing_positions": finishing,
    }
    print(json.dumps(output))


if __name__ == "__main__":
    main()
